name: "Build Uberhand"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build-Uberhand:
    name: "Release"
    runs-on: "ubuntu-latest"
    container: devkitpro/devkita64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: ovlmenu.ovl